### ISSUE TITLE
Unlock OTP secrets

### ISSUE THREAD

**Issue by maxmonz69** [dkosmari/gnome-shell-extension-totp#4]
When I click on the menu Unlock OTP secrets... I get this error:

no such secret at /org/freedesktop/secrets/collection/login/122

If I open settings I see all the OTP I created.

What's the problem?

**Comment by dkosmari** [comment]
Marking this as an invalid bug, as it looks like a known bug inside gnome-keyring.

**Comment by schmidtw** [comment]
I got into this endless loop, too.  I tried restarting the gnome-keyring-daemon with no luck.  I simply want to undo the setting I set so it doesn't block my usage now...

**Comment by schmidtw** [comment]
I had to perform:
```
killall gnome-keyring-daemon
gnome-keyring-daemon --start --components=secrets
```

to finally get things working again.
