### ISSUE TITLE
GNOME 47 Support

### ISSUE THREAD

**Issue by ccjmne** [dkosmari/gnome-shell-extension-totp#6]
Hey,

Thanks for the excellent extension!
GNOME 47 was released recently and this extension isn't compatible with that new version.

Could you upgrade it to the new version? Is there anything I can do to help?

Many thanks.

**Comment by dkosmari** [comment]
I tested on GNOME 47, the extension works perfectly. I submitted an update to EGO to enable it on 47, the update should be available in a couple of days.

**Comment by ccjmne** [comment]
Excellent, thank you very much, @dkosmari!
